// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Voteable struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Question             string   `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Answers              []string `protobuf:"bytes,3,rep,name=answers,proto3" json:"answers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Voteable) Reset()         { *m = Voteable{} }
func (m *Voteable) String() string { return proto.CompactTextString(m) }
func (*Voteable) ProtoMessage()    {}
func (*Voteable) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Voteable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Voteable.Unmarshal(m, b)
}
func (m *Voteable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Voteable.Marshal(b, m, deterministic)
}
func (m *Voteable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Voteable.Merge(m, src)
}
func (m *Voteable) XXX_Size() int {
	return xxx_messageInfo_Voteable.Size(m)
}
func (m *Voteable) XXX_DiscardUnknown() {
	xxx_messageInfo_Voteable.DiscardUnknown(m)
}

var xxx_messageInfo_Voteable proto.InternalMessageInfo

func (m *Voteable) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Voteable) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

func (m *Voteable) GetAnswers() []string {
	if m != nil {
		return m.Answers
	}
	return nil
}

type CreateVoteableRequest struct {
	Question             string   `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Answers              []string `protobuf:"bytes,2,rep,name=answers,proto3" json:"answers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateVoteableRequest) Reset()         { *m = CreateVoteableRequest{} }
func (m *CreateVoteableRequest) String() string { return proto.CompactTextString(m) }
func (*CreateVoteableRequest) ProtoMessage()    {}
func (*CreateVoteableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *CreateVoteableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVoteableRequest.Unmarshal(m, b)
}
func (m *CreateVoteableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVoteableRequest.Marshal(b, m, deterministic)
}
func (m *CreateVoteableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVoteableRequest.Merge(m, src)
}
func (m *CreateVoteableRequest) XXX_Size() int {
	return xxx_messageInfo_CreateVoteableRequest.Size(m)
}
func (m *CreateVoteableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVoteableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVoteableRequest proto.InternalMessageInfo

func (m *CreateVoteableRequest) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

func (m *CreateVoteableRequest) GetAnswers() []string {
	if m != nil {
		return m.Answers
	}
	return nil
}

type CreateVoteableResponse struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateVoteableResponse) Reset()         { *m = CreateVoteableResponse{} }
func (m *CreateVoteableResponse) String() string { return proto.CompactTextString(m) }
func (*CreateVoteableResponse) ProtoMessage()    {}
func (*CreateVoteableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *CreateVoteableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVoteableResponse.Unmarshal(m, b)
}
func (m *CreateVoteableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVoteableResponse.Marshal(b, m, deterministic)
}
func (m *CreateVoteableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVoteableResponse.Merge(m, src)
}
func (m *CreateVoteableResponse) XXX_Size() int {
	return xxx_messageInfo_CreateVoteableResponse.Size(m)
}
func (m *CreateVoteableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVoteableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVoteableResponse proto.InternalMessageInfo

func (m *CreateVoteableResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type ListVoteableRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListVoteableRequest) Reset()         { *m = ListVoteableRequest{} }
func (m *ListVoteableRequest) String() string { return proto.CompactTextString(m) }
func (*ListVoteableRequest) ProtoMessage()    {}
func (*ListVoteableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *ListVoteableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVoteableRequest.Unmarshal(m, b)
}
func (m *ListVoteableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVoteableRequest.Marshal(b, m, deterministic)
}
func (m *ListVoteableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVoteableRequest.Merge(m, src)
}
func (m *ListVoteableRequest) XXX_Size() int {
	return xxx_messageInfo_ListVoteableRequest.Size(m)
}
func (m *ListVoteableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVoteableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListVoteableRequest proto.InternalMessageInfo

type ListVoteableResponse struct {
	Votables             []*Voteable `protobuf:"bytes,1,rep,name=votables,proto3" json:"votables,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListVoteableResponse) Reset()         { *m = ListVoteableResponse{} }
func (m *ListVoteableResponse) String() string { return proto.CompactTextString(m) }
func (*ListVoteableResponse) ProtoMessage()    {}
func (*ListVoteableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *ListVoteableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVoteableResponse.Unmarshal(m, b)
}
func (m *ListVoteableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVoteableResponse.Marshal(b, m, deterministic)
}
func (m *ListVoteableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVoteableResponse.Merge(m, src)
}
func (m *ListVoteableResponse) XXX_Size() int {
	return xxx_messageInfo_ListVoteableResponse.Size(m)
}
func (m *ListVoteableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVoteableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListVoteableResponse proto.InternalMessageInfo

func (m *ListVoteableResponse) GetVotables() []*Voteable {
	if m != nil {
		return m.Votables
	}
	return nil
}

type ListVoteablesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListVoteablesResponse) Reset()         { *m = ListVoteablesResponse{} }
func (m *ListVoteablesResponse) String() string { return proto.CompactTextString(m) }
func (*ListVoteablesResponse) ProtoMessage()    {}
func (*ListVoteablesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *ListVoteablesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVoteablesResponse.Unmarshal(m, b)
}
func (m *ListVoteablesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVoteablesResponse.Marshal(b, m, deterministic)
}
func (m *ListVoteablesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVoteablesResponse.Merge(m, src)
}
func (m *ListVoteablesResponse) XXX_Size() int {
	return xxx_messageInfo_ListVoteablesResponse.Size(m)
}
func (m *ListVoteablesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVoteablesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListVoteablesResponse proto.InternalMessageInfo

type CastVoteRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	AnswerIndex          int64    `protobuf:"varint,2,opt,name=answer_index,json=answerIndex,proto3" json:"answer_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CastVoteRequest) Reset()         { *m = CastVoteRequest{} }
func (m *CastVoteRequest) String() string { return proto.CompactTextString(m) }
func (*CastVoteRequest) ProtoMessage()    {}
func (*CastVoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *CastVoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CastVoteRequest.Unmarshal(m, b)
}
func (m *CastVoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CastVoteRequest.Marshal(b, m, deterministic)
}
func (m *CastVoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CastVoteRequest.Merge(m, src)
}
func (m *CastVoteRequest) XXX_Size() int {
	return xxx_messageInfo_CastVoteRequest.Size(m)
}
func (m *CastVoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CastVoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CastVoteRequest proto.InternalMessageInfo

func (m *CastVoteRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *CastVoteRequest) GetAnswerIndex() int64 {
	if m != nil {
		return m.AnswerIndex
	}
	return 0
}

type CastVoteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CastVoteResponse) Reset()         { *m = CastVoteResponse{} }
func (m *CastVoteResponse) String() string { return proto.CompactTextString(m) }
func (*CastVoteResponse) ProtoMessage()    {}
func (*CastVoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *CastVoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CastVoteResponse.Unmarshal(m, b)
}
func (m *CastVoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CastVoteResponse.Marshal(b, m, deterministic)
}
func (m *CastVoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CastVoteResponse.Merge(m, src)
}
func (m *CastVoteResponse) XXX_Size() int {
	return xxx_messageInfo_CastVoteResponse.Size(m)
}
func (m *CastVoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CastVoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CastVoteResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Voteable)(nil), "api.Voteable")
	proto.RegisterType((*CreateVoteableRequest)(nil), "api.CreateVoteableRequest")
	proto.RegisterType((*CreateVoteableResponse)(nil), "api.CreateVoteableResponse")
	proto.RegisterType((*ListVoteableRequest)(nil), "api.ListVoteableRequest")
	proto.RegisterType((*ListVoteableResponse)(nil), "api.ListVoteableResponse")
	proto.RegisterType((*ListVoteablesResponse)(nil), "api.ListVoteablesResponse")
	proto.RegisterType((*CastVoteRequest)(nil), "api.CastVoteRequest")
	proto.RegisterType((*CastVoteResponse)(nil), "api.CastVoteResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x41, 0x4f, 0xc3, 0x20,
	0x1c, 0xc5, 0xed, 0x6a, 0xb4, 0xfb, 0xcf, 0xaa, 0xc1, 0x55, 0x09, 0x5e, 0x2a, 0xa7, 0x9a, 0x98,
	0x1e, 0xe6, 0xc9, 0xa3, 0xd9, 0x41, 0x8d, 0x7a, 0xa9, 0x66, 0x57, 0xc3, 0x1c, 0x31, 0x24, 0xa6,
	0xd4, 0x42, 0xa7, 0x1f, 0xd7, 0x8f, 0x62, 0x06, 0xa3, 0x8e, 0x5a, 0x6f, 0xe5, 0x3d, 0xf8, 0xf1,
	0xfe, 0xaf, 0x40, 0xac, 0x78, 0xbd, 0x14, 0xaf, 0x3c, 0xaf, 0x6a, 0xa9, 0x25, 0x0a, 0x59, 0x25,
	0xe8, 0x33, 0x44, 0x33, 0xa9, 0x39, 0x9b, 0xbf, 0x73, 0x84, 0x60, 0xbb, 0x69, 0xc4, 0x02, 0x07,
	0x69, 0x90, 0x0d, 0x0b, 0xf3, 0x8d, 0x08, 0x44, 0x1f, 0x0d, 0x57, 0x5a, 0xc8, 0x12, 0x0f, 0x8c,
	0xde, 0xae, 0x11, 0x86, 0x5d, 0x56, 0xaa, 0x4f, 0x5e, 0x2b, 0x1c, 0xa6, 0x61, 0x36, 0x2c, 0xdc,
	0x92, 0x3e, 0x42, 0x32, 0xad, 0x39, 0xd3, 0xdc, 0xb1, 0x0b, 0x6e, 0x4e, 0x79, 0xb8, 0xe0, 0x7f,
	0xdc, 0xc0, 0xc7, 0x5d, 0xc0, 0x71, 0x17, 0xa7, 0x2a, 0x59, 0xaa, 0xde, 0xc8, 0x34, 0x81, 0xa3,
	0x07, 0xa1, 0x74, 0xe7, 0x6a, 0x7a, 0x0d, 0x63, 0x5f, 0x5e, 0x23, 0xce, 0x21, 0x5a, 0x4a, 0xbd,
	0x92, 0x14, 0x0e, 0xd2, 0x30, 0x1b, 0x4d, 0xe2, 0x9c, 0x55, 0x22, 0x6f, 0x37, 0xb6, 0x36, 0x3d,
	0x81, 0x64, 0x13, 0xa1, 0x1c, 0x83, 0xde, 0xc2, 0xc1, 0x94, 0x59, 0xc3, 0x4d, 0xda, 0x57, 0xe6,
	0x19, 0xec, 0xd9, 0x91, 0x5e, 0x44, 0xb9, 0xe0, 0x5f, 0xa6, 0xd0, 0xb0, 0x18, 0x59, 0xed, 0x6e,
	0x25, 0x51, 0x04, 0x87, 0xbf, 0x24, 0x4b, 0x9f, 0x7c, 0x07, 0x10, 0xcf, 0xa4, 0x16, 0xe5, 0xdb,
	0x93, 0xfd, 0x81, 0xe8, 0x1e, 0xf6, 0xfd, 0x42, 0x10, 0x31, 0x99, 0x7b, 0x4b, 0x27, 0xa7, 0xbd,
	0xde, 0x3a, 0xfa, 0x16, 0xba, 0x81, 0xd8, 0x9b, 0x0a, 0x61, 0xb3, 0xbf, 0xa7, 0x43, 0x42, 0xfe,
	0x38, 0x6a, 0x03, 0x74, 0x05, 0x91, 0xcb, 0x8e, 0xc6, 0xf6, 0x4e, 0xbf, 0x14, 0x92, 0x74, 0x54,
	0x77, 0x74, 0xbe, 0x63, 0x9e, 0xe4, 0xe5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x71, 0x34, 0x3b,
	0x89, 0xa3, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// VotingServiceClient is the client API for VotingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VotingServiceClient interface {
	CreateVoteable(ctx context.Context, in *CreateVoteableRequest, opts ...grpc.CallOption) (*CreateVoteableResponse, error)
	ListVoteables(ctx context.Context, in *ListVoteableRequest, opts ...grpc.CallOption) (*ListVoteablesResponse, error)
	CastVote(ctx context.Context, in *CastVoteRequest, opts ...grpc.CallOption) (*CastVoteResponse, error)
}

type votingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVotingServiceClient(cc grpc.ClientConnInterface) VotingServiceClient {
	return &votingServiceClient{cc}
}

func (c *votingServiceClient) CreateVoteable(ctx context.Context, in *CreateVoteableRequest, opts ...grpc.CallOption) (*CreateVoteableResponse, error) {
	out := new(CreateVoteableResponse)
	err := c.cc.Invoke(ctx, "/api.VotingService/CreateVoteable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *votingServiceClient) ListVoteables(ctx context.Context, in *ListVoteableRequest, opts ...grpc.CallOption) (*ListVoteablesResponse, error) {
	out := new(ListVoteablesResponse)
	err := c.cc.Invoke(ctx, "/api.VotingService/ListVoteables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *votingServiceClient) CastVote(ctx context.Context, in *CastVoteRequest, opts ...grpc.CallOption) (*CastVoteResponse, error) {
	out := new(CastVoteResponse)
	err := c.cc.Invoke(ctx, "/api.VotingService/CastVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VotingServiceServer is the server API for VotingService service.
type VotingServiceServer interface {
	CreateVoteable(context.Context, *CreateVoteableRequest) (*CreateVoteableResponse, error)
	ListVoteables(context.Context, *ListVoteableRequest) (*ListVoteablesResponse, error)
	CastVote(context.Context, *CastVoteRequest) (*CastVoteResponse, error)
}

// UnimplementedVotingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedVotingServiceServer struct {
}

func (*UnimplementedVotingServiceServer) CreateVoteable(ctx context.Context, req *CreateVoteableRequest) (*CreateVoteableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVoteable not implemented")
}
func (*UnimplementedVotingServiceServer) ListVoteables(ctx context.Context, req *ListVoteableRequest) (*ListVoteablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVoteables not implemented")
}
func (*UnimplementedVotingServiceServer) CastVote(ctx context.Context, req *CastVoteRequest) (*CastVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CastVote not implemented")
}

func RegisterVotingServiceServer(s *grpc.Server, srv VotingServiceServer) {
	s.RegisterService(&_VotingService_serviceDesc, srv)
}

func _VotingService_CreateVoteable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVoteableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VotingServiceServer).CreateVoteable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.VotingService/CreateVoteable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VotingServiceServer).CreateVoteable(ctx, req.(*CreateVoteableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VotingService_ListVoteables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVoteableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VotingServiceServer).ListVoteables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.VotingService/ListVoteables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VotingServiceServer).ListVoteables(ctx, req.(*ListVoteableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VotingService_CastVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CastVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VotingServiceServer).CastVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.VotingService/CastVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VotingServiceServer).CastVote(ctx, req.(*CastVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VotingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.VotingService",
	HandlerType: (*VotingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVoteable",
			Handler:    _VotingService_CreateVoteable_Handler,
		},
		{
			MethodName: "ListVoteables",
			Handler:    _VotingService_ListVoteables_Handler,
		},
		{
			MethodName: "CastVote",
			Handler:    _VotingService_CastVote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
